server:
  port: 8084

spring:
  application:
    name: ai-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos


deepseek:
  api-key: a5b265ef-77f1-4e8a-a79e-7972c3de70c6
  api-url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
